name: quanda
description: quanda.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # getX状态管理
  get: ^4.6.5
  # 网络请求
  http: ^0.13.4
  # 网络请求
  dio: ^4.0.6
  # 检测网络连接
  connectivity_plus: ^2.3.2
  # json转model
  json_annotation: ^4.5.0
  # 腾讯im
  tencent_im_sdk_plugin: ^4.0.2
  # lottie
  lottie: ^1.3.0
  # 左滑删除
  flutter_slidable: ^1.3.0
  # 缓存网络图片
  cached_network_image: ^3.2.1
  # 权限管理
  permission_handler: ^10.0.0
  # 保存图片
  image_gallery_saver: ^1.7.1
  # loading
  flutter_spinkit: ^5.1.0
  # toast
  fluttertoast: ^8.0.9
  # 本地化
  flutter_localizations:
    sdk: flutter
  # 持久存储
  shared_preferences: ^2.0.15
  # 图片选择器
  image_picker: ^0.8.5+3
  # 图片查看器
  photo_view: ^0.14.0
  # 城市选择器
  city_pickers: ^1.1.1
  # 地理编码
  geocoding: ^2.0.4
  # 汉字转拼音
  lpinyin: ^2.0.3
  # 下拉刷新上拉加载
  easy_refresh: ^3.0.2+2
  # 二维码扫码
  barcode_scan2: ^4.2.1
  # 短信验证码自动获取
  pinput: ^2.2.11
  # 视频播放器
  video_player: ^2.4.5
  # 二维码生成器
  qr_flutter: ^4.0.0
  # 轮播图
  card_swiper: ^2.0.4
  # 高德定位
  amap_flutter_location: ^3.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:

  uses-material-design: true

  assets:
    - img/bottomNavigation/
    - img/Icon/
    - img/bigIcon/

  fonts:
    - family: Rany
      fonts:
        - asset: font/Rany-Bold.otf